// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TestButton = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_TestButton, 100);
lv_obj_set_height( ui_TestButton, 50);
lv_obj_set_x( ui_TestButton, 17 );
lv_obj_set_y( ui_TestButton, 16 );
lv_obj_set_flex_flow(ui_TestButton,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_TestButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_TestButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_TestButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_TestButton);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -42 );
lv_obj_set_y( ui_Label1, -69 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );

}
